use role {{ env.DATAOPS_CATALOG_SOLUTION_PREFIX }}_DATA_SCIENTIST;

CREATE OR REPLACE NOTEBOOK {{ env.DATAOPS_DATABASE }}.ANALYTICS.{{ env.DATAOPS_CATALOG_SOLUTION_PREFIX }}_Feature_Store_Overview
FROM '@{{ env.DATAOPS_DATABASE }}.ANALYTICS.NOTEBOOK/Feature_Store_Overview'
MAIN_FILE = 'Feature_Store_Overview.ipynb'
QUERY_WAREHOUSE = '{{ env.DATAOPS_CATALOG_SOLUTION_PREFIX }}_DS_WH';
ALTER NOTEBOOK {{ env.DATAOPS_DATABASE }}.ANALYTICS.{{ env.DATAOPS_CATALOG_SOLUTION_PREFIX }}_Feature_Store_Overview ADD LIVE VERSION FROM LAST;

CREATE OR REPLACE NOTEBOOK {{ env.DATAOPS_DATABASE }}.ANALYTICS.{{ env.DATAOPS_CATALOG_SOLUTION_PREFIX }}_Fine_Tuning_LLM_with_Cortex_AI
FROM '@{{ env.DATAOPS_DATABASE }}.ANALYTICS.NOTEBOOK/Fine_Tuning_LLM_with_Cortex_AI'
MAIN_FILE = 'Fine_Tuning_LLM_with_Cortex_AI.ipynb'
QUERY_WAREHOUSE = '{{ env.DATAOPS_CATALOG_SOLUTION_PREFIX }}_DS_WH';
ALTER NOTEBOOK {{ env.DATAOPS_DATABASE }}.ANALYTICS.{{ env.DATAOPS_CATALOG_SOLUTION_PREFIX }}_Fine_Tuning_LLM_with_Cortex_AI ADD LIVE VERSION FROM LAST;

CREATE OR REPLACE NOTEBOOK {{ env.DATAOPS_DATABASE }}.ANALYTICS.{{ env.DATAOPS_CATALOG_SOLUTION_PREFIX }}_Getting_Started_with_Snowflake_Cortex_ML_Based_Functions
FROM '@{{ env.DATAOPS_DATABASE }}.ANALYTICS.NOTEBOOK/Getting_Started_with_Snowflake_Cortex_ML-Based_Functions'
MAIN_FILE = 'Getting_Started_with_Snowflake_Cortex_ML-Based_Functions.ipynb'
QUERY_WAREHOUSE = '{{ env.DATAOPS_CATALOG_SOLUTION_PREFIX }}_DS_WH';
ALTER NOTEBOOK {{ env.DATAOPS_DATABASE }}.ANALYTICS.{{ env.DATAOPS_CATALOG_SOLUTION_PREFIX }}_Getting_Started_with_Snowflake_Cortex_ML_Based_Functions ADD LIVE VERSION FROM LAST;

CREATE OR REPLACE NOTEBOOK {{ env.DATAOPS_DATABASE }}.ANALYTICS.{{ env.DATAOPS_CATALOG_SOLUTION_PREFIX }}_Getting_Started_with_Container_Runtime
FROM '@{{ env.DATAOPS_DATABASE }}.ANALYTICS.NOTEBOOK/Getting_Started_with_Container_Runtime'
MAIN_FILE = 'Getting_Started_with_Container_Runtime.ipynb'
COMPUTE_POOL='{{ env.DATAOPS_CATALOG_SOLUTION_PREFIX }}_GPU_5_S_POOL'
QUERY_WAREHOUSE = '{{ env.DATAOPS_CATALOG_SOLUTION_PREFIX }}_DS_WH'
RUNTIME_NAME='SYSTEM$GPU_RUNTIME';
ALTER NOTEBOOK {{ env.DATAOPS_DATABASE }}.ANALYTICS.{{ env.DATAOPS_CATALOG_SOLUTION_PREFIX }}_Getting_Started_with_Container_Runtime ADD LIVE VERSION FROM LAST;
ALTER NOTEBOOK {{ env.DATAOPS_DATABASE }}.ANALYTICS.{{ env.DATAOPS_CATALOG_SOLUTION_PREFIX }}_Getting_Started_with_Container_Runtime set external_access_integrations = ("{{ env.DATAOPS_CATALOG_SOLUTION_PREFIX }}_pipy_access_integration");

CREATE OR REPLACE NOTEBOOK {{ env.DATAOPS_DATABASE }}.ANALYTICS.{{ env.DATAOPS_CATALOG_SOLUTION_PREFIX }}_Hyperparameter_Tuning_with_sklearn
FROM '@{{ env.DATAOPS_DATABASE }}.ANALYTICS.NOTEBOOK/Hyperparameter_Tuning_with_sklearn'
MAIN_FILE = 'Hyperparameter_Tuning_with_sklearn.ipynb'
QUERY_WAREHOUSE = '{{ env.DATAOPS_CATALOG_SOLUTION_PREFIX }}_DS_WH';
ALTER NOTEBOOK {{ env.DATAOPS_DATABASE }}.ANALYTICS.{{ env.DATAOPS_CATALOG_SOLUTION_PREFIX }}_Hyperparameter_Tuning_with_sklearn ADD LIVE VERSION FROM LAST;

CREATE OR REPLACE NOTEBOOK {{ env.DATAOPS_DATABASE }}.ANALYTICS.{{ env.DATAOPS_CATALOG_SOLUTION_PREFIX }}_Partitioned_ml_model
FROM '@{{ env.DATAOPS_DATABASE }}.ANALYTICS.NOTEBOOK/Partitioned_ml_model'
MAIN_FILE = 'partitioned_ml_model.ipynb'
QUERY_WAREHOUSE = '{{ env.DATAOPS_CATALOG_SOLUTION_PREFIX }}_DS_WH';
ALTER NOTEBOOK {{ env.DATAOPS_DATABASE }}.ANALYTICS.{{ env.DATAOPS_CATALOG_SOLUTION_PREFIX }}_Partitioned_ml_model ADD LIVE VERSION FROM LAST;

CREATE OR REPLACE NOTEBOOK {{ env.DATAOPS_DATABASE }}.ANALYTICS.{{ env.DATAOPS_CATALOG_SOLUTION_PREFIX }}_xgboost_on_gpu
FROM '@{{ env.DATAOPS_DATABASE }}.ANALYTICS.NOTEBOOK/xgboost_on_gpu'
MAIN_FILE = 'xgboost_on_gpu.ipynb'
COMPUTE_POOL='{{ env.DATAOPS_CATALOG_SOLUTION_PREFIX }}_POOL'
QUERY_WAREHOUSE = '{{ env.DATAOPS_CATALOG_SOLUTION_PREFIX }}_DS_WH'
RUNTIME_NAME='SYSTEM$GPU_RUNTIME';
ALTER NOTEBOOK {{ env.DATAOPS_DATABASE }}.ANALYTICS.{{ env.DATAOPS_CATALOG_SOLUTION_PREFIX }}_xgboost_on_gpu ADD LIVE VERSION FROM LAST;
ALTER NOTEBOOK {{ env.DATAOPS_DATABASE }}.ANALYTICS.{{ env.DATAOPS_CATALOG_SOLUTION_PREFIX }}_xgboost_on_gpu set external_access_integrations = ("{{ env.DATAOPS_CATALOG_SOLUTION_PREFIX }}_pipy_access_integration");

CREATE OR REPLACE NOTEBOOK {{ env.DATAOPS_DATABASE }}.ANALYTICS.{{ env.DATAOPS_CATALOG_SOLUTION_PREFIX }}_Predicting_Ad_Spend_ROI_with_Snowpark_ML
FROM '@{{ env.DATAOPS_DATABASE }}.ANALYTICS.NOTEBOOK/Predicting_Ad_Spend_ROI_with_Snowpark_ML'
MAIN_FILE = 'Predicting_Ad_Spend_ROI_with_Snowpark_ML.ipynb'
QUERY_WAREHOUSE = '{{ env.DATAOPS_CATALOG_SOLUTION_PREFIX }}_DS_WH';
ALTER NOTEBOOK {{ env.DATAOPS_DATABASE }}.ANALYTICS.{{ env.DATAOPS_CATALOG_SOLUTION_PREFIX }}_Predicting_Ad_Spend_ROI_with_Snowpark_ML ADD LIVE VERSION FROM LAST;